//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppli.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJediList", ReplyAction="http://tempuri.org/IService1/GetJediListResponse")]
        WcfService1.EntitiesWS.JediWS[] GetJediList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJediList", ReplyAction="http://tempuri.org/IService1/GetJediListResponse")]
        System.Threading.Tasks.Task<WcfService1.EntitiesWS.JediWS[]> GetJediListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStadeList", ReplyAction="http://tempuri.org/IService1/GetStadeListResponse")]
        WcfService1.EntitiesWS.StadeWS[] GetStadeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStadeList", ReplyAction="http://tempuri.org/IService1/GetStadeListResponse")]
        System.Threading.Tasks.Task<WcfService1.EntitiesWS.StadeWS[]> GetStadeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatchList", ReplyAction="http://tempuri.org/IService1/GetMatchListResponse")]
        WcfService1.EntitiesWS.MatchWS[] GetMatchList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatchList", ReplyAction="http://tempuri.org/IService1/GetMatchListResponse")]
        System.Threading.Tasks.Task<WcfService1.EntitiesWS.MatchWS[]> GetMatchListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTournamentList", ReplyAction="http://tempuri.org/IService1/GetTournamentListResponse")]
        WcfService1.EntitiesWS.TournoiWS[] GetTournamentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTournamentList", ReplyAction="http://tempuri.org/IService1/GetTournamentListResponse")]
        System.Threading.Tasks.Task<WcfService1.EntitiesWS.TournoiWS[]> GetTournamentListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebAppli.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebAppli.ServiceReference1.IService1>, WebAppli.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService1.EntitiesWS.JediWS[] GetJediList() {
            return base.Channel.GetJediList();
        }
        
        public System.Threading.Tasks.Task<WcfService1.EntitiesWS.JediWS[]> GetJediListAsync() {
            return base.Channel.GetJediListAsync();
        }
        
        public WcfService1.EntitiesWS.StadeWS[] GetStadeList() {
            return base.Channel.GetStadeList();
        }
        
        public System.Threading.Tasks.Task<WcfService1.EntitiesWS.StadeWS[]> GetStadeListAsync() {
            return base.Channel.GetStadeListAsync();
        }
        
        public WcfService1.EntitiesWS.MatchWS[] GetMatchList() {
            return base.Channel.GetMatchList();
        }
        
        public System.Threading.Tasks.Task<WcfService1.EntitiesWS.MatchWS[]> GetMatchListAsync() {
            return base.Channel.GetMatchListAsync();
        }
        
        public WcfService1.EntitiesWS.TournoiWS[] GetTournamentList() {
            return base.Channel.GetTournamentList();
        }
        
        public System.Threading.Tasks.Task<WcfService1.EntitiesWS.TournoiWS[]> GetTournamentListAsync() {
            return base.Channel.GetTournamentListAsync();
        }
    }
}
